name: Deploy Sphinx documentation to Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "pages"
  pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Environment variables
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    permissions:
      pages: write
      id-token: write
    
    steps:
      # use the latest version of the checkout action
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          documentation_path: './source'  # Path to Sphinx source files
          requirements_path: './requirements.txt'  # Path to requirements file
          python_version: '3.10'  # Version of Python
          sphinx_version: '5.3'  # Version of Sphinx
          cache: true  # Enable cache to speed up documentation building
        
# Set concurrency group to avoid multiple builds
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
